# Generated by Django 5.0.7 on 2024-12-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, verbose_name='اسم طريقة الدفع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='الشعار')),
                ('activate_state', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('country', models.CharField(max_length=50, verbose_name='الدولة')),
                ('currency', models.CharField(default='RYL', max_length=25, verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['-activate_state', 'method_name'],
            },
        ),
        migrations.CreateModel(
            name='ChoosePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=66, null=True, verbose_name='رقم التحويل')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='الوصف')),
                ('hospitals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='hospitals.hospital', verbose_name='المستشفيات')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_option', to='payments.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('payment_status_name', models.CharField(max_length=50, verbose_name='اسم حالة الدفع')),
                ('status_code', models.IntegerField(verbose_name='رمز الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'حالة الدفع',
                'verbose_name_plural': 'حالات الدفع',
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('payment_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الفرعي')),
                ('payment_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_totalamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('payment_currency', models.CharField(default='RYL', max_length=25, verbose_name='العملة')),
                ('payment_note', models.TextField(blank=True, max_length=300, null=True, verbose_name='ملاحظات')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('e_pay', 'دفع إلكتروني')], default='cash', max_length=20, verbose_name='نوع الدفع')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='الحجز')),
                ('payment_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.choosepayment', verbose_name='طريقة الدفع')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentstatus', verbose_name='حالة الدفع')),
            ],
            options={
                'verbose_name': 'فاتورة دفع',
                'verbose_name_plural': 'فواتير الدفع',
                'ordering': ['-payment_date'],
            },
        ),
    ]
