# Generated by Django 5.0.7 on 2025-01-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_logos/', verbose_name='شعار')),
                ('currency', models.CharField(default='RYL', max_length=25, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status_name', models.CharField(max_length=50, verbose_name='اسم حالة الدفع')),
                ('status_code', models.IntegerField(verbose_name='رمز الحالة')),
            ],
            options={
                'verbose_name': 'حالة الدفع',
                'verbose_name_plural': 'حالات الدفع',
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='HospitalPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(max_length=50, verbose_name='رقم الآيبان')),
                ('description', models.TextField(verbose_name='تعليمات الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_payment_methods', to='hospitals.hospital', verbose_name='المستشفى')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentoption', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طريقة دفع المستشفى',
                'verbose_name_plural': 'طرق دفع المستشفى',
                'unique_together': {('hospital', 'payment_option')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('payment_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الفرعي')),
                ('payment_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('payment_totalamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('payment_currency', models.CharField(default='RYL', max_length=25, verbose_name='العملة')),
                ('payment_note', models.TextField(blank=True, max_length=300, null=True, verbose_name='ملاحظات')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('e_pay', 'دفع إلكتروني')], default='cash', max_length=20, verbose_name='نوع الدفع')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='الحجز')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.hospitalpaymentmethod', verbose_name='طريقة الدفع')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentstatus', verbose_name='حالة الدفع')),
            ],
            options={
                'verbose_name': 'فاتورة دفع',
                'verbose_name_plural': 'فواتير الدفع',
                'ordering': ['-payment_date'],
            },
        ),
    ]
