# Generated by Django 5.0.7 on 2024-12-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='slug',
        ),
    ]
