# Generated by Django 5.1.3 on 2024-12-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'نجمة واحدة'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], default=5, help_text='تقييم من 1 إلى 5 نجوم', verbose_name='التقييم')),
                ('review', models.TextField(help_text='اكتب رأيك عن تجربتك في المستشفى', verbose_name='التعليق')),
                ('status', models.BooleanField(default=True, help_text='هل المراجعة مرئية للجميع؟', verbose_name='نشط')),
                ('has_reservation', models.BooleanField(default=False, help_text='هل قام المستخدم بالحجز في المستشفى؟', verbose_name='لديه حجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
