# Generated by Django 5.0.7 on 2024-12-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
                ('qr_title', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('google_play_icon', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('google_play_url', models.TextField(null=True)),
                ('apple_store_icon', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('apple_store_url', models.TextField(null=True)),
                ('app_photo', models.ImageField(upload_to='home/components/app/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/faq/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('header_icon', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/icons/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image1', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image2', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image3', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertner_image', models.ImageField(blank=True, null=True, upload_to='home/components/partners/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='home/components/work/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('show_at_home', models.BooleanField(default=True)),
                ('faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.faqsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/testimonial/')),
                ('review', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('show_at_home', models.BooleanField(default=True)),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.testimonialsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='home/components/work/icons/')),
                ('show_at_home', models.BooleanField(default=True)),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.worksection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
