# Generated by Django 5.1.4 on 2024-12-23 06:30

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
                ('qr_title', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('google_play_icon', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('google_play_url', models.TextField(null=True)),
                ('apple_store_icon', models.ImageField(blank=True, null=True, upload_to='home/components/app/')),
                ('apple_store_url', models.TextField(null=True)),
                ('app_photo', models.ImageField(upload_to='home/components/app/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/faq/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('header_icon', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/icons/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image1', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image2', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
                ('sub_image3', models.ImageField(blank=True, null=True, upload_to='home/components/homebanner/')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertner_image', models.ImageField(blank=True, null=True, upload_to='home/components/partners/')),
                ('show_at_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('default_currency', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('currency_icon', models.CharField(max_length=10)),
                ('default_language', models.CharField(max_length=100)),
                ('currency_Icon_position', models.IntegerField(choices=[(0, 'left'), (1, 'right')], default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='home/components/work/')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(default='privacypolicy', max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('show_at_home', models.BooleanField(default=True)),
                ('faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.faqsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(default='terms and conditions', max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/components/testimonial/')),
                ('review', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('show_at_home', models.BooleanField(default=True)),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.testimonialsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='home/components/work/icons/')),
                ('show_at_home', models.BooleanField(default=True)),
                ('work_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.worksection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
