# Generated by Django 5.0.7 on 2024-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerssection',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
