# Generated by Django 5.0.7 on 2024-12-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_partnerssection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerssection',
            name='status',
        ),
    ]
