# Generated by Django 5.0.7 on 2024-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_privacypolicy_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='name',
            field=models.CharField(default='privacypolicy', max_length=150),
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='name',
            field=models.CharField(default='terms and conditions', max_length=150),
        ),
    ]
