# Generated by Django 5.0.7 on 2024-12-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_privacypolicy_name_termsconditions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('default_currency', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('currency_icon', models.CharField(max_length=10)),
                ('default_language', models.CharField(max_length=100)),
                ('currency_Icon_position', models.IntegerField(choices=[(0, 'left'), (1, 'right')], default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='home/components/setting/')),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.TextField()),
                ('google_map_link', models.TextField()),
            ],
        ),
    ]
