# Generated by Django 5.0.7 on 2024-12-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_setting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='google_map_link',
        ),
    ]
