# Generated by Django 5.0.7 on 2024-12-14 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'قيد الانتظار'), (1, 'تمت الموافقة'), (2, 'مرفوض'), (3, 'ملغي')], default=0, help_text='الحالة الحالية لطلب التسجيل', verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(help_text='الاسم الكامل لمالك المستشفى', max_length=100, verbose_name='اسم المالك')),
                ('hotel_name', models.CharField(help_text='اسم المستشفى كما سيظهر في النظام', max_length=100, verbose_name='اسم المستشفى')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='رقم الهاتف الرسمي للمالك', max_length=20, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. يسمح بإدخال من 9 إلى 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('business_license_number', models.CharField(blank=True, help_text='رقم الرخصة للمستشفى', max_length=50, null=True, verbose_name='رقم الرخصة الطبية')),
                ('document_path', models.FileField(help_text='المستندات الرسمية للمستشفى (رخصة العمل، السجل التجاري، إلخ)', upload_to='hospital_documents/%Y/%m/%d/', verbose_name='مستندات المستشفى')),
                ('verify_number', models.CharField(help_text='رقم التحقق الخاص بطلب التسجيل', max_length=50, unique=True, verbose_name='رقم التحقق')),
                ('attached_documents', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات المسؤول حول الطلب', null=True, verbose_name='ملاحظات المسؤول')),
                ('password', models.CharField(help_text='كلمة السر المؤقتة للحساب', max_length=255, verbose_name='كلمة السر')),
                ('verify_code', models.CharField(max_length=6)),
                ('block_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب حساب مستشفى',
                'verbose_name_plural': 'طلبات حسابات المستشفيات',
                'ordering': ['-application_date'],
            },
        ),
    ]
