# Generated by Django 5.1.4 on 2024-12-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('hospital_name', models.CharField(max_length=100, verbose_name='اسم المستشفى')),
                ('manager_full_name', models.CharField(max_length=255, verbose_name='اسم مدير المستشفى')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للمدير')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المدير')),
                ('manager_password', models.CharField(help_text='كلمة المرور التي سيتم استخدامها لحساب مدير المستشفى', max_length=128, verbose_name='كلمة المرور')),
                ('hospital_location', models.CharField(max_length=255, verbose_name='موقع المستشفى')),
                ('commercial_record', models.FileField(help_text='يرجى رفع نسخة من السجل التجاري للمستشفى', upload_to='hospital_documents/', verbose_name='السجل التجاري')),
                ('medical_license', models.FileField(help_text='يرجى رفع نسخة من الترخيص الطبي للمستشفى', upload_to='hospital_documents/', verbose_name='الترخيص الطبي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول الطلب', null=True, verbose_name='ملاحظات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
            ],
            options={
                'verbose_name': 'طلب فتح حساب مستشفى',
                'verbose_name_plural': 'طلبات فتح حساب مستشفى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hospital_images/')),
                ('sub_title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('show_at_home', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(max_length=14)),
                ('phone_type', models.CharField(choices=[('landline', 'هاتف أرضي'), ('mobile', 'هاتف محمول')], default='mobile', max_length=50, verbose_name='نوع الهاتف')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.city', verbose_name='المدينة')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
