# Generated by Django 5.0.7 on 2024-12-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0002_phonenumber_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetail',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty'),
            preserve_default=False,
        ),
    ]
