# Generated by Django 5.1.3 on 2024-12-17 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('hospital_name', models.CharField(max_length=100, verbose_name='اسم المستشفى')),
                ('manager_full_name', models.CharField(max_length=255, verbose_name='اسم مدير المستشفى')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للمدير')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المدير')),
                ('hospital_location', models.CharField(max_length=255, verbose_name='موقع المستشفى')),
                ('commercial_record', models.FileField(help_text='يرجى رفع نسخة من السجل التجاري للمستشفى', upload_to='hospital_documents/', verbose_name='السجل التجاري')),
                ('medical_license', models.FileField(help_text='يرجى رفع نسخة من الترخيص الطبي للمستشفى', upload_to='hospital_documents/', verbose_name='الترخيص الطبي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول الطلب', null=True, verbose_name='ملاحظات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hospital_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'verbose_name': 'طلب فتح حساب مستشفى',
                'verbose_name_plural': 'طلبات فتح حساب مستشفى',
                'ordering': ['-created_at'],
            },
        ),
    ]
