# Generated by Django 5.1.3 on 2024-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitalaccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalaccountrequest',
            name='manager_password',
            field=models.CharField(default=1, help_text='كلمة المرور التي سيتم استخدامها لحساب مدير المستشفى', max_length=128, verbose_name='كلمة المرور'),
            preserve_default=False,
        ),
    ]
