# Generated by Django 5.0.7 on 2024-12-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitaldetail_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hospitaldetail',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='slug',
        ),
    ]
