# Generated by Django 5.1.3 on 2024-12-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_hospital_hospital_manager_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_manager_id',
            new_name='hospital_manager',
        ),
    ]
