<<<<<<< HEAD
# Generated by Django 5.0.7 on 2025-01-03 12:18
=======
# Generated by Django 5.1.4 on 2025-01-02 18:18
>>>>>>> origin/dashboard-patients

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
            options={
                'verbose_name': 'المفضلات',
                'verbose_name_plural': 'المفضلات',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('0', 'ذكر'), ('1', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_pictures/', verbose_name='صورة الملف الشخصي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
