<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-23 06:30
=======
# Generated by Django 5.1.3 on 2024-12-24 20:28
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
            ],
            options={
                'verbose_name': 'المفضلات',
                'verbose_name_plural': 'المفضلات',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('0', 'ذكر'), ('1', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_pictures/', verbose_name='صورة الملف الشخصي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
<<<<<<< HEAD
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='زمرة الدم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
=======
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923
            ],
            options={
                'abstract': False,
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='doctors.doctor', verbose_name='الطبيب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='patients.patients', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'المفضلات',
                'verbose_name_plural': 'المفضلات',
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor')],
            },
        ),
=======
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923
    ]
