# Generated by Django 5.0.7 on 2024-12-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='slug',
        ),
    ]
