# Generated by Django 3.2.25 on 2024-12-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=2, max_length=3, verbose_name='زمرة الدم'),
            preserve_default=False,
        ),
    ]
