<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-23 06:30
=======
# Generated by Django 5.1.3 on 2024-12-24 20:28
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='doctors.doctor'),
        ),
    ]
