# Generated by Django 3.2.25 on 2024-12-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('consultation', 'استشارة'), ('surgery', 'جراحة'), ('checkup', 'فحص دوري'), ('emergency', 'طوارئ')], default=1, max_length=20, verbose_name='الغرض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('in_person', 'شخصي'), ('online', 'عن بُعد')], default=2, max_length=20, verbose_name='نوع الحجز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل'),
        ),
    ]
