# Generated by Django 5.0.7 on 2024-12-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('doctors', '0003_alter_doctorschedules_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='doctors.doctorschedules'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='doctors.doctorshifts'),
        ),
    ]
