# Generated by Django 3.2.25 on 2024-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20241217_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('new', 'جديد'), ('followup', 'متابع')], max_length=20, verbose_name='نوع الحجز'),
        ),
    ]
