# Generated by Django 5.0.7 on 2024-12-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'جدول الطبيب',
                'verbose_name_plural': 'جداول الأطباء',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialty/')),
                ('show_at_home', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sub_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('about', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('show_at_home', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='المعدل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'جدول اسعار الطبيب',
                'verbose_name_plural': 'جداول اسعار الأطباء',
            },
        ),
    ]
