<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-23 06:30
=======
# Generated by Django 5.1.3 on 2024-12-24 20:28
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('gender', models.IntegerField(choices=[(1, 'male'), (0, 'famel')], default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sub_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('about', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('show_at_home', models.BooleanField(default=True)),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923
            name='DoctorPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
            ],
            options={
                'verbose_name': 'جدول اسعار الطبيب',
                'verbose_name_plural': 'جداول اسعار الأطباء',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('available_slots', models.PositiveIntegerField(default=0, verbose_name='عدد المواعيد المتاحة')),
            ],
            options={
                'verbose_name': 'جدول الطبيب',
                'verbose_name_plural': 'جداول الأطباء',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التخصص')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialty/', verbose_name='صورة التخصص')),
                ('show_at_home', models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'abstract': False,
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('birthday', models.DateField(verbose_name='تاريخ الميلاد')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='الصورة الشخصية')),
                ('gender', models.IntegerField(choices=[(1, 'ذكر'), (0, 'أنثى')], default=1, verbose_name='الجنس')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('experience', models.IntegerField(default=0, verbose_name='الخبرة')),
                ('sub_title', models.CharField(max_length=255, verbose_name='العنوان الفرعي')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='رابط الطبيب')),
                ('about', models.TextField(verbose_name='نبذة عن الطبيب')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('show_at_home', models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='المنشى')),
            ],
            options={
                'abstract': False,
            },
        ),
=======
>>>>>>> 17a6cc346d6933bc45c5346f29d0bec0ec6e5923
    ]
