# Generated by Django 5.0.7 on 2024-12-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0003_hospitaldetail_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='doctorschedules',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedules',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_schedules', to='hospitals.hospital'),
        ),
    ]
