# Generated by Django 5.0.7 on 2024-12-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedules',
            options={'ordering': ['day', 'doctor']},
        ),
        migrations.RemoveField(
            model_name='doctorschedules',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='doctorschedules',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedules',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='day',
            field=models.CharField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], max_length=20),
        ),
        migrations.CreateModel(
            name='DoctorShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.PositiveIntegerField(default=0)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('doctor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='doctors.doctorschedules')),
            ],
        ),
    ]
