# Generated by Django 3.2.25 on 2024-12-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitaldetail_specialty'),
        ('doctors', '0002_doctor_hospitals_doctorschedules_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name'], 'verbose_name': 'طبيب', 'verbose_name_plural': 'الأطباء'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'تخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.TextField(verbose_name='نبذة عن الطبيب'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='hospitals.Hospital', verbose_name='المستشفيات'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='show_at_home',
            field=models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sub_title',
            field=models.CharField(max_length=255, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='available_slots',
            field=models.PositiveIntegerField(default=0, help_text='عدد المواعيد المتاحة لهذا اليوم.', verbose_name='عدد المواعيد المتاحة'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='day',
            field=models.CharField(max_length=20, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='الطبيب'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='end_time',
            field=models.TimeField(verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_schedules', to='hospitals.hospital', verbose_name='المستشفى'),
        ),
        migrations.AlterField(
            model_name='doctorschedules',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialty/', verbose_name='صورة التخصص'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم التخصص'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='show_at_home',
            field=models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='status',
            field=models.BooleanField(default=True, verbose_name='الحالة'),
        ),
    ]
