# Generated by Django 5.0.7 on 2024-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_hospitals_doctorschedules_doctor_and_more'),
        ('hospitals', '0003_hospitaldetail_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='doctors', to='hospitals.hospital'),
        ),
    ]
