# Generated by Django 5.0.7 on 2024-12-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_hospitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='slug',
        ),
    ]
