# Generated by Django 5.0.7 on 2024-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_hospitals_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'famel')], default=1),
        ),
    ]
