# Generated by Django 5.1.4 on 2024-12-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('status', models.CharField(choices=[('0', 'غير مقروء'), ('1', 'مقروء')], default='0', max_length=50, verbose_name='الحالة')),
                ('notification_type', models.CharField(choices=[('0', 'معلومة'), ('1', 'تحذير'), ('2', 'نجاح'), ('3', 'خطأ')], max_length=50, verbose_name='نوع الإشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-send_time'],
            },
        ),
    ]
