# Generated by Django 5.0.7 on 2024-12-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='slug',
        ),
    ]
